In [63]:
import pandas as pd

Working with JSON

In [64]:
df=pd.read_json('train.json')

In [65]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.0388
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.6760
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.8850
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,4.0100
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,2.5300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.1820
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.2020
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.2680
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-31,1774915201,0.2680

Working with SQL

In [67]:
import sqlite3
conn=sqlite3.connect('students.db')
cursor=conn.cursor()

with open('students.sql', 'r') as f:
  sql_script=f.read()

cursor.executescript(sql_script)

conn.commit()

In [72]:
df=pd.read_sql_query('SELECT * FROM students', conn)

In [73]:
df

   id    name  age  gender  marks
0   1     Ali   22    Male     85
1   2    Sara   21  Female     90
2   3   Ahmed   23    Male     78
3   4  Ayesha   22  Female     88
4   5   Usman   24    Male     67
5   6    Zara   20  Female     95